# Generated by Django 3.1.3 on 2020-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='work_out',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='work_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
