# Generated by Django 3.1.3 on 2020-11-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201121_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='time_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request', to='api.timesheet'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
