# Generated by Django 3.1.3 on 2020-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201121_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='work_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
